### ISSUE TITLE
go-neb sometimes start without a Matrix access token available

### ISSUE THREAD

**Issue by delroth** [NixOS/nixos-org-configurations#330]
```
# cat /var/run/go-neb/config.yaml
clients:
- AccessToken:
  AutoJoinRooms: true
  DisplayName: Bot
  HomeServerUrl: https://nixos.ems.host
  Sync: true
  UserId: '@bot:nixos.org'
```

The AccessToken wasn't properly substituted in the ExecStartPre, likely because the key file hadn't been copied yet. There's likely a systemd service dependency missing here.
